### ISSUE TITLE
server list

### ISSUE THREAD

**Issue by gyokiss** [ionos-cloud/module-ansible#22]
### Current SDK Version
5.0.5

### Use-case
List all deployed server from a  datacenter 
If there ais a deployment, than it is neccessary to check the server names. Here would be great, if the server module able to deliver back the full list of server names. 

### References

my temporary solution, to query directly the API url, but there have I circumveniate the "items" keyword from json reply.

**Comment by jbuchhammer** [comment]
Hi @gyokiss , for us it looks like implementation of custom facts is requested.
In general, it's a good addition to the existing code and if done, it should be done for all resources.

However, I, personally, still not get a grasp on what the use-case and it's approach is.
Having a list is fine, but if you want to check s.th. particular you already have to know _what_ you are looking for (i.e. by name or by UUID).
Can you please explain it in more detail?

The same holds for #23 , I'll X-ref there

**Comment by hkicsi** [comment]
Hi, 

the usecase: I'm currently building the environment automation. The deployment would be started from ansible-tower or rundeck.  The deployment should be done unattended. My issue is- hostnames are not autogenerated, so I have to check it - in datacenter the choosen hostname is free (otherwise can it lead strange situations). 
My first step: check the hostname. Sadly the API created - through url - a little bit less ansible friendly as would be best. ( in response we have a "block" named "item") - my workaround is two times jmeshquery.

gyokiss

**Comment by avirtopeanu-ionos** [comment]
Hello,  A new module has been added: `server-info`, on the [v6.2.0](https://galaxy.ansible.com/ionoscloudsdk/ionoscloud) release. Sadly, we are no longer adding new features or enhancements on version 5, we're addressing only bugs. We encourage you to update the module to the version 6.

Have a nice day!
